### ISSUE TITLE
Som kunde vil jeg have en tabel over afgange til og fra en bestemt destination, så jeg kan se mulige afgange. 30 points

### ISSUE THREAD

**Issue by JoacimV** [coej94/3SemesterProject#2]
Som kunde vil jeg have en tabel over afgange til og fra en bestemt destination, så jeg kan se mulige afgange. 30 point.

**Comment by Joacim12** [comment]
task 1

**Comment by JoacimV** [comment]
Hente data via api

fetch("http://localhost:8084/seedMaven/api/demoall/CPH/2/2017-05-06T00:00:00.000Z",{method:"GET"}).then(function(res){ return res.json(); })
.then(function(data){ console.log( JSON.stringify( data ) ) })

**Comment by Joacim12** [comment]
fetch data fra wowondo til browser via javascript

**Comment by JoacimV** [comment]
fetch data fra wowondo til browser via javascript

**Comment by JoacimV** [comment]
lav en tabel der viser data i html

**Comment by JoacimV** [comment]
lav en webserver der kan hente data asynkront fra forskellige flyselskaber
